### PR TITLE
small changes to the Sheets APIs

### PR DESCRIPTION
**Pull request by borisfaure**
Hi!
I'm using your sheets crate and I wanted to update more than on cells but couldn't with the current API.
I've changed it to be able to do so. While I was at it, I've also changed `Sheets::get_values()` to be more regular.
I've bumped the version of the crate due to those API changes and made `cio/Cargo.toml` use the local version of the sheets crate.
I've patched the existing calls to reflect those changes.

I've made multiple commits so that it's easier to pick one or more of those changes.

### CODE REVIEW

**Comment by borisfaure** [comment]
@jessfraz should I try to resolve those conflicts?

**Comment by IceDynamix** [comment]
Please do, that'd be great

**Comment by borisfaure** [comment]
I had to switch to rust nightly but it `cargo check`s fine.

**Comment by borisfaure** [comment]
@IceDynamix  Is it worth rebasing again?

**Comment by borisfaure** [comment]
@jessfraz Is this repository open to outside contributions?

**Comment by jessfraz** [comment]
closing as i moved this lib to be generated from the spec here: https://github.com/oxidecomputer/third-party-api-clients

**Pull request closed without merging**
